sitename: "Stanislav Goremykin Blog"
baseURL: "/"
languageCode: en-us
title: "Stanislavgm Blog"
author: Stanislav Goremykin

enableEmoji: true
hasCJKLanguage: false
# You can change code highlight theme
pygmentsstyle: "tango"
pygmentscodefences: true

# if you want to add html to your markdown
markup:
  goldmark:
    renderer:
      unsafe: true

# Links of the navbar
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: CV
      url: https://gohugo.io/installation/linux/
      weight: 2
    - name: GitHub
      url: https://github.com/stanislavmg/
      weight: 3
    - name: "LinkedIn"
      url: https://www.linkedin.com/in/stanislav-goremykin-195889254/
      weight: 4

# You can add languages!
# do not expect it to work out of the box
# https://gohugo.io/content-management/multilingual/
defaultContentLanguage: ru
languages:
  en:
    LanguageName: English
    # contentDir: content/english
  ru:
    LanguageName: русский
    # contentDir: content/russian

params:
  sitename: "Stanislav Goremykin Blog"
  # it will produce: copyrights (c) 2022 joe
  copyrights: stanislavmg
  # set default homepage list (what section to list pages from)
  # default: global
  # currently available options (global, blog)
  defaultList: global
  # list 3 items of every section
  # you can use a section specific list
  # to list n items of that section.
  # see ./layouts/partials/bloglist.html for example
  paginationLen: 3
  # path to the favicon directory
  # see ./layouts/_defaults/baseof.html line #30 to line #37
  # faviconpath: "/img/favicon"
  # projects will show in the index page
  myprojects:
    - name: "School 42 Piscine"
      description: "26-ти дневный интенсив для поступления в международную школу программирования"
      url: https://github.com/stanislavmg/Piscine-C-Ecole-42.git
  # link to more projects
  # show your github repositories as example
  # or create your own page.
  projectsURL: https://example.com

  # a brief about me
  brief_about: <center>Заметки о программировании и информационных технологиях</center>

# and don't forget
theme: kaslaanka
