baseURL = "https://example.com/"
languageCode = "en-us"
title = "Example Lekh Site"
sectionPagesMenu = 'main'
theme = "test"

[params]
Name = "Заметки о программировании и информационных технологиях"
About = ""
Email = "stanislavgoremykin.ra@gmail.com"
Resume = "/index.html" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

# [[params.profiles]]
# name = "О сайте"
# url = "/about/index.html"

[[params.profiles]]
name = "GitHub"
url = "https://github.com/stanislavmg"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/stanislav-goremykin-195889254/"